/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/colors/': RouteRecordInfo<'/colors/', '/colors', Record<never, never>, Record<never, never>>,
    '/colors/advanced': RouteRecordInfo<'/colors/advanced', '/colors/advanced', Record<never, never>, Record<never, never>>,
    '/colors/basic': RouteRecordInfo<'/colors/basic', '/colors/basic', Record<never, never>, Record<never, never>>,
    '/docs/': RouteRecordInfo<'/docs/', '/docs', Record<never, never>, Record<never, never>>,
    '/docs/about': RouteRecordInfo<'/docs/about', '/docs/about', Record<never, never>, Record<never, never>>,
    '/docs/install': RouteRecordInfo<'/docs/install', '/docs/install', Record<never, never>, Record<never, never>>,
    '/examples': RouteRecordInfo<'/examples', '/examples', Record<never, never>, Record<never, never>>,
  }
}
